function [descriptor] = pb_descriptor_QDLIB__Response()
%pb_descriptor_QDLIB__Response Returns the descriptor for message Response.
%   function [descriptor] = pb_descriptor_QDLIB__Response()
%
%   See also pb_read_QDLIB__Response
  
  descriptor = struct( ...
    'name', 'Response', ...
    'full_name', 'QDLIB.Response', ...
    'filename', 'IACmds.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'response', ...
        'full_name', 'QDLIB.Response.response', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(14), ...
        'matlab_type', uint32(10), ...
        'wire_type', uint32(0), ...
        'label', uint32(2), ...
        'default_value', int32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'int32')), ...
        'write_function', @(x) typecast(int32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'msg', ...
        'full_name', 'QDLIB.Response.msg', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  
