function [descriptor] = pb_descriptor_QDLIB__MultiStateIdentifier()
%pb_descriptor_QDLIB__MultiStateIdentifier Returns the descriptor for message MultiStateIdentifier.
%   function [descriptor] = pb_descriptor_QDLIB__MultiStateIdentifier()
%
%   See also pb_read_QDLIB__MultiStateIdentifier
  
  descriptor = struct( ...
    'name', 'MultiStateIdentifier', ...
    'full_name', 'QDLIB.MultiStateIdentifier', ...
    'filename', 'FileSingleHeader.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'state', ...
        'full_name', 'QDLIB.MultiStateIdentifier.state', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(5), ...
        'matlab_type', uint32(1), ...
        'wire_type', uint32(0), ...
        'label', uint32(2), ...
        'default_value', int32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'int32')), ...
        'write_function', @(x) typecast(int32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  
