function [descriptor] = pb_descriptor_QDLIB__GridSystemHeader__dim_description_t()
%pb_descriptor_QDLIB__GridSystemHeader__dim_description_t Returns the descriptor for message dim_description_t.
%   function [descriptor] = pb_descriptor_QDLIB__GridSystemHeader__dim_description_t()
%
%   See also pb_read_QDLIB__GridSystemHeader__dim_description_t
  
  descriptor = struct( ...
    'name', 'dim_description_t', ...
    'full_name', 'QDLIB.GridSystemHeader.dim_description_t', ...
    'filename', 'GridSystem.pro', ...
    'containing_type', 'QDLIB.GridSystemHeader', ...
    'fields', [ ...
      struct( ...
        'name', 'size', ...
        'full_name', 'QDLIB.GridSystemHeader.dim_description_t.size', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(13), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(2), ...
        'default_value', uint32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'xmin', ...
        'full_name', 'QDLIB.GridSystemHeader.dim_description_t.xmin', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(1), ...
        'matlab_type', uint32(5), ...
        'wire_type', uint32(1), ...
        'label', uint32(2), ...
        'default_value', double(0), ...
        'read_function', @(x) typecast(x, 'double'), ...
        'write_function', @(x) typecast(double(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'xmax', ...
        'full_name', 'QDLIB.GridSystemHeader.dim_description_t.xmax', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(1), ...
        'matlab_type', uint32(5), ...
        'wire_type', uint32(1), ...
        'label', uint32(2), ...
        'default_value', double(0), ...
        'read_function', @(x) typecast(x, 'double'), ...
        'write_function', @(x) typecast(double(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);
  
