function [descriptor] = pb_descriptor_QDLIB__GridSystemHeader()
%pb_descriptor_QDLIB__GridSystemHeader Returns the descriptor for message GridSystemHeader.
%   function [descriptor] = pb_descriptor_QDLIB__GridSystemHeader()
%
%   See also pb_read_QDLIB__GridSystemHeader
  
  descriptor = struct( ...
    'name', 'GridSystemHeader', ...
    'full_name', 'QDLIB.GridSystemHeader', ...
    'filename', 'GridSystem.pro', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'dims', ...
        'full_name', 'QDLIB.GridSystemHeader.dims', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(13), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(2), ...
        'default_value', uint32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'dim', ...
        'full_name', 'QDLIB.GridSystemHeader.dim', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_QDLIB__GridSystemHeader__dim_description_t(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'data_size', ...
        'full_name', 'QDLIB.GridSystemHeader.data_size', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(4), ...
        'matlab_type', uint32(4), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint64(0), ...
        'read_function', @(x) typecast(x, 'uint64'), ...
        'write_function', @(x) typecast(uint64(x), 'uint64'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);
  
